name: Browser tests

on: pull_request

env:
  FORCE_COLOR: true

jobs:
  verify-linux:
    timeout-minutes: 30
    name: Linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # TODO: remove when GitHub fixes this https://github.com/actions/runner-images/issues/10015
      # (this workaround is practically the same what Playwright did in https://github.com/microsoft/playwright/pull/34238/files)
      - name: Workaround for Chrome sandbox issue in Ubuntu 24.04
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        env:
          FORCE_COLOR: 0
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      # build for production in CI to make sure tests can run with production build
      - name: Build specific packages for production
        run: npm run build:production

      - name: Test
        run: npm run test:browser
